### ISSUE TITLE
Debian: gnome-shell v3.16.2-4

### ISSUE THREAD

**Issue by jmauro** [vajrasky/wallpapoz#19]
Hi everyone,

There is any issue with the lastest Debian testing gnome-shell (3.16.2-4), apparently the command line `gnome-session --version` returns an empty line:

```
# gnome-session --version
# gnome-session --version --debug
gnome-session[29479]: DEBUG(+): Enabling debugging
gnome-session 3.16.0
 #
```

So https://github.com/vajrasky/wallpapoz/blob/master/share/wallpapoz/lib/wallpapoz_system.py#L66  doesn't work properly.

I don't think there is something to do except waiting for debian community to fix the issue but I just wanted to broadcast the information.

Regards,
JM

**Comment by liamquin** [comment]
A fix is to change it to use gnome shell as a fallback:
   else:
      output = os.popen("gnome-session --version")
      result = output.readlines()
      if len(result) < 1:
        output = os.popen("gnome-shell --version")
        result = output.readlines()
        version = result[0].split()[2].split('.')[0]
      else:
        version = result[0].split()[1].split('.')[0]
